import Head from 'next/head';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Image from 'next/legacy/image';
import Weather from '@/components/weather';
import Spinner from '@/components/Spinner';




export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);





  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather = (e) => {
    e.preventDefault(true);
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data)

    })
    setCity('');
    setLoading(false);

  }





  if (loading) {
    return <Spinner />;
  } else {

    return (

      <div>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* overlay */}
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]"></div>

        {/* bg image */}
        <Image src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8d2VhdGhlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=1500&q=60"
          layout='fill'
          className='object-cover w-full h-full'
        />

        {/* search form */}

        <div className="relative top-7 flex justify-between items-center max-w-[530px] w-full m-auto pt-4 text-white z-10">
          <form onSubmit={fetchWeather} className="flex justify-between items-center w-full m-auto p-3 bg-transparent border-2 border-gray-300 text-white rounded-xl">
            <div className="">
              <input
                onChange={(e) => setCity(e.target.value)}
                className=' bg-transparent border-none placeholder:text-white/95 text-white focus:outline-none text-2xl '
                type="text"
                placeholder='Search city' />
            </div>
            <button onClick={fetchWeather} className=''><BsSearch size={25} /></button>
          </form>
        </div>
        {/* Weather */}

        {weather.main && <Weather data={weather} />}


      </div>
    );
  }



}
